ignore:
  - "test/"

coverage:
  precision: 3
  range: "97...100"
  status:
    project:
      default:
        threshold: 1

parsers:
  gcov:
    branch_detection:
      conditional: no
      loop: no
      method: no
      macro: no
